import Nav from "@/app/component/nav";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Footer from "./component/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="main">
          <Nav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
